package util;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;

@WebServlet("/greetings")
public class GreetingsServlet extends HttpServlet {
    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        PrintWriter out = resp.getWriter();
        out.println("<!DOCTYPE html>");
        out.println("<html lang='ru'>");
        out.println("<head>");
        out.println("    <meta charset='UTF-8'>");
        out.println("    <title>Знакомство</title>");
        out.println("    <link href='https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css' rel='stylesheet'>");
        out.println("    <style>");
        out.println("        body {");
        out.println("            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);");
        out.println("            min-height: 100vh;");
        out.println("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;");
        out.println("            padding: 20px;");
        out.println("        }");
        out.println("        .container {");
        out.println("            max-width: 700px;");
        out.println("            margin: 50px auto;");
        out.println("        }");
        out.println("        .story-card {");
        out.println("            background: white;");
        out.println("            border-radius: 20px;");
        out.println("            box-shadow: 0 10px 40px rgba(0,0,0,0.2);");
        out.println("            padding: 40px;");
        out.println("            animation: fadeIn 0.8s ease-in;");
        out.println("        }");
        out.println("        @keyframes fadeIn {");
        out.println("            from { opacity: 0; transform: translateY(20px); }");
        out.println("            to { opacity: 1; transform: translateY(0); }");
        out.println("        }");
        out.println("        .story-text {");
        out.println("            font-size: 1.1rem;");
        out.println("            line-height: 1.6;");
        out.println("            color: #333;");
        out.println("            margin-bottom: 30px;");
        out.println("        }");
        out.println("        .greeting-text {");
        out.println("            background: #f8f9fa;");
        out.println("            padding: 20px;");
        out.println("            border-radius: 15px;");
        out.println("            border-left: 4px solid #667eea;");
        out.println("            margin-bottom: 30px;");
        out.println("            font-style: italic;");
        out.println("        }");
        out.println("        .form-control {");
        out.println("            border-radius: 10px;");
        out.println("            border: 2px solid #e0e0e0;");
        out.println("            padding: 12px;");
        out.println("            font-size: 1rem;");
        out.println("        }");
        out.println("        .form-control:focus {");
        out.println("            border-color: #667eea;");
        out.println("            box-shadow: 0 0 0 0.2rem rgba(102, 126, 234, 0.25);");
        out.println("        }");
        out.println("        .btn-start {");
        out.println("            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);");
        out.println("            border: none;");
        out.println("            border-radius: 10px;");
        out.println("            padding: 12px 30px;");
        out.println("            font-size: 1.1rem;");
        out.println("            font-weight: bold;");
        out.println("            transition: transform 0.2s;");
        out.println("        }");
        out.println("        .btn-start:hover {");
        out.println("            transform: translateY(-2px);");
        out.println("            background: linear-gradient(135deg, #764ba2 0%, #667eea 100%);");
        out.println("        }");
        out.println("        h2 {");
        out.println("            color: #667eea;");
        out.println("            margin-bottom: 25px;");
        out.println("            font-weight: bold;");
        out.println("        }");
        out.println("    </style>");
        out.println("</head>");
        out.println("<body>");
        out.println("<div class='container'>");
        out.println("    <div class='story-card'>");
        out.println("        <h2 class='text-center'>📖 Начало истории</h2>");
        out.println("        <div class='story-text'>");
        out.println("            <p>Ты на вчерашней тусовке познакомился с одной девушкой. Она тебе очень понравилась. И вот в один день ты пригласил её на свидание.</p>");
        out.println("        </div>");
        out.println("        <div class='greeting-text'>");
        out.println("            <p>\"Привет, Мерелин! Меня зовут <strong>______</strong>. Мы виделись на тусовке в Лос-Анджелесе у Питта. Ты мне очень понравилась, и я хочу пригласить тебя на свидание завтра вечером.\"</p>");
        out.println("        </div>");
        out.println("        <form action='/start' method='post'>");
        out.println("            <div class='mb-4'>");
        out.println("                <label for='playerName' class='form-label fw-bold'>Как тебя зовут?</label>");
        out.println("                <input type='text' class='form-control' id='playerName' name='playerName' required placeholder='Введите ваше имя...'>");
        out.println("            </div>");
        out.println("            <div class='text-center'>");
        out.println("                <button type='submit' class='btn btn-primary btn-start'>✨ Начать свидание ✨</button>");
        out.println("            </div>");
        out.println("        </form>");
        out.println("    </div>");
        out.println("</div>");
        out.println("</body>");
        out.println("</html>");
    }
    }

